name: CI / CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint & test
        run: |
          npm run lint
          npm test

      - name: Build
        run: npm run build

      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy to GAE
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
